<?php

$horarios = array(
    array('hora' => '00:15', 'destino'=> 'Necochea', 'empresa'=> 'El Rápido'),
    array('hora' => '00:30', 'destino'=> 'Pergamino', 'empresa'=> 'El Rápido'),
    array('hora' => '00:45', 'destino'=> 'Santa Rosa', 'empresa'=> 'El Rápido'),
    array('hora' => '01:10', 'destino'=> 'Capital', 'empresa'=> 'La Estrella'),
    array('hora' => '01:15', 'destino'=> 'La Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '01:40', 'destino'=> 'La Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '01:45', 'destino'=> 'Capital', 'empresa'=> 'El Rápido'),
    array('hora' => '01:45', 'destino'=> 'Capital', 'empresa'=> 'Río Paraná'),
    array('hora' => '02:00', 'destino'=> 'La Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '02:40', 'destino'=> 'Lincoln', 'empresa'=> 'El Rápido'),
    array('hora' => '02:50', 'destino'=> 'Bahía Blanca', 'empresa'=> 'Río Paraná'),
    array('hora' => '03:40', 'destino'=> 'Mar del Plata', 'empresa'=> 'Costera Criolla'),
    array('hora' => '04:05', 'destino'=> 'Necochea', 'empresa'=> 'Río Paraná'),
    array('hora' => '04:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '04:50', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '05:00', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '05:00', 'destino'=> 'Mar del Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '05:15', 'destino'=> 'Necochea', 'empresa'=> 'El Rápido'),
    array('hora' => '05:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '05:50', 'destino'=> 'Mar del Plata', 'empresa'=> 'Plus Ultra'),
    array('hora' => '06:00', 'destino'=> 'La Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '06:00', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido Argentino'),
    array('hora' => '06:05', 'destino'=> 'Mar del Plata', 'empresa'=> 'AutoTrans SJ-MDP'),
    array('hora' => '06:30', 'destino'=> 'Barker-Cacique', 'empresa'=> 'Río Paraná'),
    array('hora' => '06:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'Zenit'),
    array('hora' => '06:40', 'destino'=> 'Mar del Plata', 'empresa'=> 'San Juan - MDP'),
    array('hora' => '07:00', 'destino'=> 'Capital', 'empresa'=> 'Río Paraná'),
    array('hora' => '07:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '07:30', 'destino'=> 'Capital', 'empresa'=> 'La Estrella'),
    array('hora' => '08:45', 'destino'=> 'Bolivar', 'empresa'=> 'El Rápido'),
    array('hora' => '08:55', 'destino'=> 'Mar del Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '09:00', 'destino'=> 'Mar del Plata', 'empresa'=> 'Flecha Bus'),
    array('hora' => '09:20', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '10:00', 'destino'=> 'Capital', 'empresa'=> 'El Rápido'),
    array('hora' => '10:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '11:15', 'destino'=> 'Pehuajó', 'empresa'=> 'El Rápido'),
    array('hora' => '11:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '11:30', 'destino'=> 'Vela', 'empresa'=> 'Expresso Vela'),
    array('hora' => '11:55', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '12:00', 'destino'=> 'Barker-Cacique', 'empresa'=> 'Río Paraná'),
    array('hora' => '12:20', 'destino'=> 'Capital', 'empresa'=> 'El Rápido'),
    array('hora' => '12:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'Plus Ultra'),
    array('hora' => '12:45', 'destino'=> 'Necochea', 'empresa'=> 'Río Paraná'),
    array('hora' => '13:00', 'destino'=> 'B. Juárez', 'empresa'=> 'Río Paraná'),
    array('hora' => '13:00', 'destino'=> 'Bahía Blanca', 'empresa'=> 'Río Paraná'),
    array('hora' => '13:15', 'destino'=> 'Capital', 'empresa'=> 'Río Paraná'),
    array('hora' => '13:30', 'destino'=> 'Capital', 'empresa'=> 'La Estrella'),
    array('hora' => '13:40', 'destino'=> 'La Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '13:40', 'destino'=> 'Necochea', 'empresa'=> 'El Rápido'),
    array('hora' => '14:25', 'destino'=> 'Bragado', 'empresa'=> 'El Rápido'),
    array('hora' => '14:30', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '14:45', 'destino'=> 'Córdoba', 'empresa'=> 'El Rápido'),
    array('hora' => '15:00', 'destino'=> 'La Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '15:15', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '15:20', 'destino'=> 'Mendoza', 'empresa'=> 'AndesMar'),
    array('hora' => '15:35', 'destino'=> 'Tucumán', 'empresa'=> 'Río Paraná'),
    array('hora' => '15:35', 'destino'=> 'Mendoza', 'empresa'=> 'El Rápido Argentino'),
    array('hora' => '15:35', 'destino'=> 'Tucumán', 'empresa'=> 'Flecha Bus'),
    array('hora' => '15:45', 'destino'=> 'Necochea', 'empresa'=> 'Río Paraná'),
    array('hora' => '15:45', 'destino'=> 'Córdoba', 'empresa'=> 'Plus Ultra'),
    array('hora' => '15:55', 'destino'=> 'Bolivar', 'empresa'=> 'El Rápido'),
    array('hora' => '16:05', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '16:25', 'destino'=> 'Capital', 'empresa'=> 'El Rápido'),
    array('hora' => '17:15', 'destino'=> 'Capital', 'empresa'=> 'Río Paraná'),
    array('hora' => '17:45', 'destino'=> 'Bahía Blanca', 'empresa'=> 'Río Paraná'),
    array('hora' => '18:00', 'destino'=> 'Mar del Plata', 'empresa'=> 'Río Paraná'),
    array('hora' => '18:00', 'destino'=> 'Córdoba', 'empresa'=> 'Zenit'),
    array('hora' => '18:10', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '18:15', 'destino'=> 'Capital', 'empresa'=> 'La Estrella'),
    array('hora' => '19:10', 'destino'=> 'Olavarría', 'empresa'=> 'El Rápido'),
    array('hora' => '19:45', 'destino'=> 'Vela', 'empresa'=> 'Expresso Vela'),
    array('hora' => '20:00', 'destino'=> 'Barker-Cacique', 'empresa'=> 'Río Paraná'),
    array('hora' => '20:00', 'destino'=> 'Necochea', 'empresa'=> 'El Rápido'),
    array('hora' => '20:10', 'destino'=> 'B. Juárez', 'empresa'=> 'Río Paraná'),
    array('hora' => '20:15', 'destino'=> 'Necochea', 'empresa'=> 'Río Paraná'),
    array('hora' => '20:15', 'destino'=> 'Córdoba', 'empresa'=> 'El Rápido'),
    array('hora' => '21:30', 'destino'=> 'Rauch', 'empresa'=> 'Río Paraná'),
    array('hora' => '22:45', 'destino'=> 'Mar del Plata', 'empresa'=> 'El Rápido'),
    array('hora' => '22:50', 'destino'=> 'Rosario', 'empresa'=> 'Costera Criolla'),
    array('hora' => '23:10', 'destino'=> 'Santa Rosa', 'empresa'=> 'El Rápido'),
    array('hora' => '23:15', 'destino'=> 'Olavarría', 'empresa'=> 'El Rápido'),
    array('hora' => '23:25', 'destino'=> 'Córdoba', 'empresa'=> 'Plus Ultra'),    
);
